GET http://localhost:3333/

###

POST http://localhost:3333/createdMovies
Content-Type: application/json

{
    "titulo": "O som da liberdade",
    "genero": "Documentario",
    "duracao": 175,
    "classificacaoEtaria": "LIVRE"
}

###

PUT http://localhost:3333/updateMovies/142
Content-Type: application/json

{
    "titulo": "O som da liberdade",
    "genero": "Documentario",
    "duracao": 205,
    "classificacaoEtaria": "LIVRE"
}

###
DELETE http://localhost:3333/deleteMovies/142

